In [1]:
import pandas as pd

In [2]:
jeff_vlc = pd.read_csv('jeff_vlc_poi.csv', sep=',', decimal='.')

In [3]:
jeff_vlc.drop(['Unnamed: 0','Unnamed: 0.1','partner_id','prtn_address_latitude','prtn_address_longitude','order_id','ord_billing_address_lat','ord_billing_address_long', 'Dist_Cliente_Tienda'],inplace=True,axis=1)

In [4]:
jeff_vlc=jeff_vlc[jeff_vlc['ord_channel_type_code']=='OFFLINE']

In [5]:
jeff_vlc_reino=jeff_vlc[jeff_vlc['prtn_code']=='REINO']

In [6]:
jeff_vlc_petxina=jeff_vlc[jeff_vlc['prtn_code']=='PETXINA']

In [7]:
jeff_vlc_reino_correlacion = jeff_vlc_reino.corr()

In [8]:
jeff_vlc_petxina_correlacion = jeff_vlc_petxina.corr()

In [9]:
jeff_vlc_reino_correlacion_simple = jeff_vlc_reino_correlacion['customer_id']
jeff_vlc_reino_correlacion_simple

customer_id    1.000000
education      0.246905
lavanderias    0.306221
tiendas        0.071268
transporte    -0.346577
gimnasios     -0.020861
parques       -0.342705
restaurante    0.190697
bancos        -0.230044
estadios      -0.112390
hospitales    -0.073528
total_poi      0.015359
Name: customer_id, dtype: float64

In [10]:
jeff_vlc_petxina_correlacion_simple = jeff_vlc_petxina_correlacion['customer_id']
jeff_vlc_petxina_correlacion_simple

customer_id    1.000000
education      0.121353
lavanderias    0.101926
tiendas        0.061449
transporte    -0.134918
gimnasios      0.024849
parques       -0.162410
restaurante    0.004297
bancos        -0.198317
estadios      -0.027511
hospitales     0.271304
total_poi     -0.016676
Name: customer_id, dtype: float64

Segundo enfoque, clasificaci√≥n de clientes. Toda valencia

In [11]:
def get_correlation_shop(in_vlc):
  customer_id_count = in_vlc[['customer_id','total_poi']]
  customer_id_count = customer_id_count.groupby(by=['customer_id']).count()
  customer_id_count=customer_id_count.reset_index(level='customer_id')
  customer_id_count = customer_id_count.rename(columns={'total_poi': 'num_operaciones'})
  result = pd.merge(customer_id_count, in_vlc, on="customer_id")
  result_final = result.drop_duplicates('customer_id')
  result_final.reset_index(inplace=True)
  result_final.drop(['customer_id','index','prtn_code','prtn_city_code','ord_channel_code','ord_channel_type_code','ord_logistics_code','ord_creation_date_time'],inplace=True,axis=1)
  return result_final

In [12]:
result_test = get_correlation_shop(jeff_vlc)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [13]:
result_test.corr()

                 num_operaciones  education  ...  hospitales  total_poi
num_operaciones         1.000000  -0.335525  ...   -0.043884  -0.038638
education              -0.335525   1.000000  ...   -0.143499   0.497124
lavanderias            -0.347741   0.900320  ...   -0.236094   0.507607
tiendas                -0.140313   0.350086  ...    0.210673   0.797883
transporte              0.411587  -0.826963  ...   -0.023800  -0.237880
gimnasios              -0.181868   0.142627  ...   -0.169331   0.087164
parques                 0.388348  -0.574302  ...   -0.079817   0.004394
restaurante            -0.188667   0.777526  ...   -0.224232   0.722731
bancos                  0.379383  -0.458334  ...   -0.096630   0.400901
estadios                0.092557  -0.252037  ...    0.319503   0.228734
hospitales             -0.043884  -0.143499  ...    1.000000  -0.073565
total_poi              -0.038638   0.497124  ...   -0.073565   1.000000

[12 rows x 12 columns]

Enfoque clasificaci√≥n, clientes. Reino

In [14]:
jeff_vlc_reino = jeff_vlc[jeff_vlc['prtn_code']=='REINO']
result_reino_test = get_correlation_shop(jeff_vlc_reino)
result_reino_test.corr()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                 num_operaciones  education  ...  hospitales  total_poi
num_operaciones         1.000000  -0.360734  ...    0.117668  -0.054029
education              -0.360734   1.000000  ...   -0.153221   0.462062
lavanderias            -0.386697   0.889975  ...   -0.279525   0.470332
tiendas                -0.035888   0.343909  ...    0.001011   0.927411
transporte              0.381285  -0.847708  ...    0.197105  -0.225108
gimnasios              -0.195842   0.340749  ...   -0.436458   0.347674
parques                 0.371037  -0.627371  ...    0.276971  -0.016586
restaurante            -0.250656   0.764747  ...   -0.180641   0.681929
bancos                  0.336810  -0.586167  ...    0.263573   0.389417
estadios                0.244555  -0.354644  ...    0.387689   0.183832
hospitales              0.117668  -0.153221  ...    1.000000   0.025071
total_poi              -0.054029   0.462062  ...    0.025071   1.000000

[12 rows x 12 columns]

Enfoque clasificaci√≥n, clientes. Petxina

In [15]:
jeff_vlc_petxina = jeff_vlc[jeff_vlc['prtn_code']=='PETXINA']
result_petxina_test = get_correlation_shop(jeff_vlc_petxina)
result_petxina_test.corr()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                 num_operaciones  education  ...  hospitales  total_poi
num_operaciones         1.000000  -0.188285  ...   -0.326921   0.087442
education              -0.188285   1.000000  ...    0.359959   0.447460
lavanderias            -0.190079   0.775400  ...    0.304872   0.473478
tiendas                -0.250224   0.639121  ...    0.469680   0.699016
transporte              0.369851  -0.705065  ...   -0.613383  -0.044923
gimnasios              -0.210495   0.083562  ...   -0.012356  -0.153771
parques                 0.379377  -0.668405  ...   -0.491134   0.110348
restaurante             0.012182   0.676016  ...    0.009083   0.746062
bancos                  0.408710  -0.427364  ...   -0.486720   0.489655
estadios               -0.037489  -0.142265  ...    0.232733   0.316384
hospitales             -0.326921   0.359959  ...    1.000000  -0.011509
total_poi               0.087442   0.447460  ...   -0.011509   1.000000

[12 rows x 12 columns]